export const SITE = {
  name: "VITA-M",
  tagline: "We Engineer Moments",
  sub: "We do not just build brands. We engineer global scale efficiency.",
  email: "business.vitam@gmail.com", // TODO: Upgrade to hello@vitam.agency
  pillars: "Brand Communication · Creative Production · Behaviour Design · Business Consulting · Startup Operations",
  founders: [
    { name: "Aditya Pawar V", role: "Chief Executive Officer", phone: "+91 74166 16897", image: "/images/team/aditya.webp", linkedin: "",
      bio: "Aditya leads VITA-M\u2019s vision and strategic direction \u2014 overseeing brand engagements, client relationships, and the agency\u2019s growth trajectory. With deep expertise in graphic design, motion graphics, and video production, he ensures every creative output meets the standard the brand demands." },
    { name: "Kirtan Tata", role: "Chief Technology Officer", phone: "+91 62813 88943", image: "/images/team/kirtan.webp", linkedin: "",
      bio: "Kirtan drives VITA-M\u2019s technology and operational infrastructure \u2014 from AI-assisted workflow design to enterprise digitisation roadmaps. He architects the systems that allow VITA-M to deliver at scale." },
  ],
};

export const SERVICES = [
  { slug: "brand-communication", name: "Brand Communication", tagline: "Strategy-led messaging that makes brands impossible to ignore.",
    desc: "Positioning strategy and brand voice architecture. Campaign conceptualisation and messaging frameworks. Audience segmentation and consumer insight mapping. SEC-compliant and regulatory-aware content creation.",
    offerings: ["Positioning strategy & brand voice architecture", "Campaign conceptualisation & messaging frameworks", "Audience segmentation & consumer insight mapping", "SEC-compliant & regulatory-aware content creation", "Social media strategy across Instagram, X, LinkedIn"] },
  { slug: "creative-production", name: "Creative Production", tagline: "Visuals, reels & content that stop the scroll and hold attention.",
    desc: "Instagram, X and LinkedIn post design and copywriting. Reels, video ads and short-form video production. Product and brand photography, visual identity rollout. Blockchain and Web3 community content. Launch campaigns, event creatives and print collateral.",
    offerings: ["Social post design & copywriting (Instagram, X, LinkedIn)", "Reels, video ads & short-form production", "Product & brand photography", "Blockchain & Web3 community content", "Launch campaigns, event creatives & print collateral"] },
  { slug: "behaviour-design", name: "Behaviour Design", tagline: "Nudges and journeys built on real consumer psychology.",
    desc: "Consumer journey mapping from real-world observation. Retail and in-store experience design. Behavioural nudge frameworks for conversion optimisation. Launch moment engineering and activation planning. Data-informed UX and decision-architecture consulting.",
    offerings: ["Consumer journey mapping from observation", "Retail & in-store experience design", "Behavioural nudge frameworks for conversion", "Launch moment engineering & activation", "Data-informed UX & decision-architecture"] },
  { slug: "business-consulting", name: "Business Consulting", tagline: "Strategic advisory, market expansion and go-to-market execution.",
    desc: "VITA-M acts as an embedded strategic partner \u2014 not just a vendor. We work alongside founders and leadership teams to identify growth vectors, resolve operational bottlenecks and build the go-to-market architecture needed to scale.",
    offerings: ["Growth vector identification & strategic advisory", "Market expansion playbooks (new cities, new segments)", "Go-to-market architecture design", "Channel partner & B2B sales model design", "Investor-ready business narrative development"] },
  { slug: "startup-operations", name: "Startup Operations", tagline: "End-to-end operational setup: tech, management, hiring & growth.",
    desc: "For early-stage and growth-stage startups, VITA-M provides the operational backbone that founders need but rarely have time to build. We plug into your team as an operational co-founder layer.",
    offerings: ["CTO-layer tech coordination & vendor selection", "Recruitment strategy, JD creation & pipeline management", "OKR frameworks & team accountability systems", "Sprint oversight & product roadmap alignment", "End-to-end executive & specialist hiring"] },
];

export const METHODOLOGY = [
  { stage: "01", name: "Observe", icon: "Search", desc: "We use contextual inquiry and in-situ observation to capture behaviours that surveys and analytics miss. Foot traffic, purchase hesitation, scroll behaviour, competitor shelf placement.", science: "Grounded in ethnographic research methodology and contextual inquiry frameworks." },
  { stage: "02", name: "Decode", icon: "Brain", desc: "We apply cognitive bias frameworks \u2014 anchoring, loss aversion, the endowment effect, status quo bias \u2014 to translate raw observations into actionable strategic levers.", science: "Built on Kahneman & Tversky\u2019s cognitive bias models and Thaler\u2019s nudge theory." },
  { stage: "03", name: "Design", icon: "Layers", desc: "We use choice architecture and nudge theory to structure every creative decision. Every visual, copy element and UX choice has a documented behavioural rationale.", science: "Applies choice architecture (Sunstein & Thaler) and framing effect principles." },
  { stage: "04", name: "Deploy", icon: "Zap", desc: "We implement continuous A/B testing with behavioural benchmarks. Measuring real consumer action against predicted behavioural models, then iterating on evidence.", science: "Continuous experimentation using Bayesian inference and behavioural prediction." },
];

export const WHY_US = [
  { num: "1", title: "Behaviour-First Strategy", desc: "We start with observation, not assumption. Strategy is built on how people actually behave \u2014 not how spreadsheets say they do." },
  { num: "2", title: "End-to-End Ownership", desc: "Communication, operations, production, consulting \u2014 one team, no handoffs, full accountability from brief to outcome." },
  { num: "3", title: "Cross-Industry Fluency", desc: "From blockchain to elevators to financial compliance \u2014 we think in outcomes and consumer psychology, not industry labels." },
  { num: "4", title: "AI & Operations Integration", desc: "We bring technology inside your business \u2014 AI-assisted workflows, automated operations and data infrastructure that actually get used." },
  { num: "5", title: "Culturally Calibrated Content", desc: "Regional language, platform-native formats, compliance-aware copy \u2014 content that lands precisely in context." },
  { num: "6", title: "Startup-Embedded Partnership", desc: "For early-stage companies, we act as the operational co-founder layer \u2014 covering tech, hiring, management systems and growth." },
];

export const SPRINTS = [
  { name: "Behavioural Brand Diagnostic", duration: "4 weeks", price: "\u20B93.5L",
    desc: "A deep-dive into your brand\u2019s behavioural health. We audit your consumer\u2019s decision-making landscape and deliver a strategic roadmap.",
    deliverables: ["Consumer behaviour audit report", "Competitor perception mapping", "Brand positioning matrix", "Cognitive bias opportunity analysis", "Strategic recommendations document", "90-minute stakeholder presentation"],
    ideal: "Brands unsure where to start, or preparing for a rebrand." },
  { name: "Brand Identity System", duration: "6 weeks", price: "\u20B95L",
    desc: "A complete visual and verbal identity built on behavioural insight. Everything your brand needs to look, sound, and feel coherent.",
    deliverables: ["Logo system & visual identity", "Colour, typography & iconography", "Brand guidelines document (40+ pages)", "Social media template system", "Brand voice & messaging framework", "Stationery & digital collateral"],
    ideal: "Startups post-funding, or traditional businesses modernising." },
  { name: "Content Ecosystem Build", duration: "8 weeks", price: "\u20B94L",
    desc: "A production-ready content engine with strategy, creative, and measurement baked in.",
    deliverables: ["Content strategy & pillar framework", "3-month editorial calendar", "24 production-ready social creatives", "4 motion graphics / video assets", "Performance measurement framework", "Monthly reporting template"],
    ideal: "Marketing teams needing volume + strategy simultaneously." },
];

export const CASE_STUDIES = [
  { slug: "sunrise-lifts", client: "Sunrise Lifts", industry: "Manufacturing \u00B7 B2B \u00B7 Elevator Solutions", region: "Andhra Pradesh & Telangana",
    headline: "Lifting a Brand Into the Digital Age",
    summary: "How we designed a structured B2B business model and digital communication strategy for one of AP & Telangana\u2019s leading elevator manufacturers.",
    challenge: "Sunrise Lifts had a strong product range but a fragmented B2B sales approach and limited presence in newer markets. The brand needed to move beyond its existing geography, formalise its commercial model and build a communication strategy that spoke directly to builders, architects and real-estate developers.",
    approach: "VITA-M designed a structured B2B business model for Sunrise \u2014 defining pricing tiers, partnership frameworks and commission structures for channel partners. Simultaneously, we built a market expansion roadmap identifying target cities and the tailored messaging strategy required for each. Social content anchored in trust, technical authority and regional affinity supported the outreach.",
    deliverables: ["B2B sales model design and channel partner framework", "Market expansion playbook for 4 new cities", "Instagram content strategy and monthly post design"],
    cards: [
      { title: "B2B Model Design", desc: "Channel partner tiers, pricing structures, co-marketing framework for builders and contractors." },
      { title: "Market Expansion", desc: "Roadmap for Hyderabad, Vijayawada, Tirupati and Guntur \u2014 messaging tailored per market." },
      { title: "Instagram Strategy", desc: "Education + aspiration approach: elevator types, safety authority, regional cultural hooks." },
      { title: "B2B Trust Content", desc: "\u2018Builders Trust Sunrise\u2019 series: case studies, feature posts and technical credibility content." },
    ],
    metrics: [{ label: "Cities expanded to", value: "4", prefix: "", suffix: "" }, { label: "B2B partner framework", value: "Complete", prefix: "", suffix: "" }, { label: "Content strategy", value: "Ongoing", prefix: "", suffix: "" }],
    color: "#F97316", images: ["/images/work/sunrise/hero.webp"] },
  { slug: "diamond-hooves", client: "Diamond Hooves", industry: "Blockchain \u00B7 Web3 NFT Gaming \u00B7 B2B Consulting",
    headline: "Building a World People Want to Live In",
    summary: "How we delivered dual-track marketing and B2B consulting for a Web3 play-to-earn horse-racing NFT ecosystem.",
    challenge: "Diamond Hooves needed to simultaneously build retail community hype on X and establish credible B2B relationships with blockchain infrastructure partners, launchpads and DeFi protocols for integrations and funding conversations.",
    approach: "VITA-M delivered on two parallel tracks. On the marketing side, we created high-energy X content that demystified the ecosystem lifecycle with character-driven artwork and infographics. On the consulting side, we developed pitch materials and a B2B outreach strategy targeting Web3 investors, launchpad platforms and ecosystem partners \u2014 translating a gaming project into a fundable business narrative.",
    deliverables: ["Blockchain ecosystem explainer content for X / Twitter", "B2B pitch deck and partner outreach strategy", "Mint Party event creatives and community hype campaign"],
    cards: [
      { title: "Ecosystem Marketing", desc: "Eat. Race. Sleep. Repeat. \u2014 lifecycle explainer posts for the Web3 community audience on X." },
      { title: "B2B Consulting", desc: "Partner pitch decks, launchpad outreach collateral and investor-ready blockchain business narrative." },
      { title: "Mint Party Campaign", desc: "15 Oct. community mobilisation: countdown content, character drops and event announcement graphics." },
      { title: "Staking Explainers", desc: "Visual breakdowns of staking mechanics, rewards and ecosystem roles \u2014 reducing technical drop-off." },
    ],
    metrics: [{ label: "Mint Party", value: "Executed", prefix: "", suffix: "" }, { label: "B2B pitch deck", value: "Delivered", prefix: "", suffix: "" }, { label: "Ecosystem content", value: "Ongoing", prefix: "", suffix: "" }],
    color: "#2DD4BF", images: ["/images/work/diamond-hooves/hero.webp"] },
  { slug: "joy", client: "JOY", industry: "AI Supply Chain \u00B7 Enterprise Digitisation",
    headline: "Engineering Efficiency at Scale",
    summary: "How we redesigned JOY\u2019s supply chain workflows with AI-assisted automation and built an enterprise digitisation roadmap for institutional partnerships.",
    challenge: "JOY \u2014 a crypto-enabled travel booking platform \u2014 was facing fragmented back-end operations with inefficient supplier coordination and booking fulfilment pipelines, and needed an enterprise-grade digital presence for institutional partnerships and large-volume B2B clients.",
    approach: "VITA-M embedded at the operations layer to redesign JOY\u2019s supply chain workflows using AI-assisted automation \u2014 reducing manual touchpoints in inventory management, vendor communication and booking reconciliation. In parallel, we built an enterprise digitisation roadmap covering CRM integration, data reporting infrastructure and client-facing portal design.",
    deliverables: ["AI-assisted supply chain workflow redesign", "Enterprise CRM and data reporting infrastructure", "Social launch campaigns and enterprise brand identity"],
    cards: [
      { title: "AI Supply Chain", desc: "Automated vendor coordination, booking reconciliation and real-time inventory sync." },
      { title: "Enterprise Ops Layer", desc: "CRM integration, reporting dashboards and B2B portal design for institutional travel clients." },
      { title: "Digitisation Roadmap", desc: "Phased enterprise digitisation plan \u2014 from MVP workflows to full-stack ops infrastructure." },
      { title: "Launch Identity", desc: "Social content and visual identity for app launch targeting crypto-savvy global travellers." },
    ],
    metrics: [{ label: "Workflow redesign", value: "Complete", prefix: "", suffix: "" }, { label: "Enterprise roadmap", value: "Delivered", prefix: "", suffix: "" }, { label: "Ops overhead", value: "Reduced", prefix: "", suffix: "" }],
    color: "#A855F7", images: ["/images/work/joy/hero.webp"] },
  { slug: "hac", client: "HAC", industry: "Finance \u00B7 SEC-Compliant Content Strategy",
    headline: "Compliance Meets Creative",
    summary: "How we developed SEC-compliant content strategy and regulatory-aware brand communication for a financial services firm.",
    challenge: "HAC needed brand communication that could navigate the strict regulatory environment of financial services while still being compelling enough to engage investors, stakeholders, and the broader market.",
    approach: "VITA-M developed a content strategy that balanced regulatory compliance with creative effectiveness \u2014 ensuring every piece of communication met SEC standards while maintaining the brand\u2019s authority and trustworthiness. We created frameworks for compliant social content, investor communications, and market-facing materials.",
    deliverables: ["SEC-compliant content strategy framework", "Investor communication templates", "Regulatory-aware social media guidelines"],
    cards: [
      { title: "SEC Compliance", desc: "Content frameworks that meet regulatory standards without sacrificing brand voice." },
      { title: "Investor Comms", desc: "Templates and systems for stakeholder communication and reporting." },
    ],
    metrics: [{ label: "Compliance framework", value: "Delivered", prefix: "", suffix: "" }, { label: "Content system", value: "Active", prefix: "", suffix: "" }],
    color: "#3B82F6", images: ["/images/work/hac/hero.webp"] },
  { slug: "ifa-adventures", client: "IFA Adventures", industry: "Travel & Tourism \u00B7 Adventure Packages \u00B7 India & International",
    headline: "From Posts to Bookings",
    summary: "How we built a destination-specific content strategy that converts wanderlust into confirmed bookings across domestic and international packages.",
    challenge: "IFA Adventures needed vivid, destination-specific content to convert wanderlust into confirmed bookings. With packages spanning Ladakh road trips, Chardham pilgrimages and international destinations like Hanoi and Vietnam, each piece of content needed to feel like a journey in itself \u2014 while still driving commercial action.",
    approach: "VITA-M created a dual-format content strategy: atmospheric destination posters with bold typography and precise pricing callouts for domestic packages, and editorial \u2018travel guide\u2019 carousel posts for international destinations \u2014 covering must-visit spots, must-try food and Instagram-worthy experiences.",
    deliverables: ["Destination poster series \u2014 domestic and international", "Ladakh, Chardham, Ratha Yatra, Ananthagiri event content", "Hanoi and Vietnam editorial guide carousel posts"],
    cards: [
      { title: "Ladakh Road Trip", desc: "7200 km motorable road \u00B7 Indian Crown Trip \u00B7 10D/9N \u20B926,899 \u2014 poster-format booking driver." },
      { title: "Chardham Pilgrimage", desc: "10D/9N sacred circuit package \u00B7 Regular departures \u2014 aspirational devotional content." },
      { title: "Hanoi Travel Guide", desc: "Must-visit lakes, must-try food, Instagram spots \u2014 editorial carousel for international awareness." },
      { title: "Ananthagiri Camp", desc: "Weekend camping at \u20B9999/person \u2014 trekking, bonfire, lake view \u2014 event-led conversion content." },
    ],
    metrics: [{ label: "Destinations covered", value: "8+", prefix: "", suffix: "" }, { label: "Content formats", value: "3", prefix: "", suffix: "" }, { label: "Booking pipeline", value: "Active", prefix: "", suffix: "" }],
    color: "#EAB308", images: ["/images/work/ifa/hero.webp"] },
];

export const STATS = [
  { value: 5, suffix: "+", label: "Clients served" },
  { value: 5, suffix: "", label: "Industries spanned" },
  { value: 3, suffix: "", label: "Countries reached" },
  { value: 5, suffix: "", label: "Service verticals" },
];

export const ASSESSMENT_QUESTIONS = [
  { id:1, cat:"Brand Foundation", q:"Do you have documented brand guidelines?", opts:[{t:"Yes, comprehensive and actively used",s:4},{t:"Yes, but outdated or rarely referenced",s:2},{t:"Partially documented",s:1},{t:"No documented guidelines",s:0}]},
  { id:2, cat:"Brand Foundation", q:"When was your last brand audit?", opts:[{t:"Within 6 months",s:4},{t:"Within 1\u20132 years",s:2},{t:"More than 2 years ago",s:1},{t:"Never conducted one",s:0}]},
  { id:3, cat:"Brand Foundation", q:"How consistent is your visual identity across touchpoints?", opts:[{t:"Highly consistent everywhere",s:4},{t:"Mostly consistent with gaps",s:2},{t:"Inconsistent across channels",s:1},{t:"No unified identity",s:0}]},
  { id:4, cat:"Digital Presence", q:"What describes your social media performance?", opts:[{t:"Strong engagement driving business results",s:4},{t:"Decent engagement, unclear business impact",s:2},{t:"Low engagement despite posting",s:1},{t:"Minimal or no presence",s:0}]},
  { id:5, cat:"Digital Presence", q:"Do you have a documented content strategy?", opts:[{t:"Yes, with pillars, calendar and KPIs",s:4},{t:"Loosely defined",s:2},{t:"We post reactively",s:1},{t:"No content strategy",s:0}]},
  { id:6, cat:"Digital Presence", q:"Does your website represent your brand quality?", opts:[{t:"Yes \u2014 modern, fast, on-brand",s:4},{t:"Functional but dated",s:2},{t:"Actively misrepresents our quality",s:1},{t:"We don\u2019t have a website",s:0}]},
  { id:7, cat:"Consumer Understanding", q:"Have you conducted consumer behaviour research?", opts:[{t:"Yes, qualitative and quantitative",s:4},{t:"Some informal research",s:2},{t:"We rely on assumptions",s:1},{t:"Never done any",s:0}]},
  { id:8, cat:"Consumer Understanding", q:"Do you know your top 3 purchase decision triggers?", opts:[{t:"Yes, validated through research",s:4},{t:"Hypotheses but unvalidated",s:2},{t:"Think we know but unsure",s:1},{t:"Haven\u2019t identified them",s:0}]},
  { id:9, cat:"Consumer Understanding", q:"Do you track metrics beyond vanity?", opts:[{t:"Yes \u2014 conversion, CAC, CLV, attribution",s:4},{t:"Some conversion tracking",s:2},{t:"Mostly vanity metrics",s:1},{t:"No meaningful tracking",s:0}]},
  { id:10, cat:"Growth Readiness", q:"What is your biggest brand challenge?", opts:[{t:"Scaling to new markets",s:4},{t:"Converting awareness to revenue",s:3},{t:"Building identity from scratch",s:2},{t:"Don\u2019t know where to start",s:0}]},
  { id:11, cat:"Growth Readiness", q:"Monthly marketing budget range?", opts:[{t:"Above \u20B95L/month",s:4},{t:"\u20B92\u20135L/month",s:3},{t:"\u20B950K\u20132L/month",s:2},{t:"Under \u20B950K/month",s:1}]},
  { id:12, cat:"Growth Readiness", q:"Timeline for brand improvement?", opts:[{t:"Immediate \u2014 this month",s:4},{t:"Within next quarter",s:3},{t:"Within 6 months",s:2},{t:"Exploring, no fixed timeline",s:1}]},
];
